- CONTRIBUTING.md
- README.md
- client/src/styles/Home.css
- client/src/styles/OPD.css
#13  i just created both readme and contribution just give it a preview
> update readme and contribution

- client/src/styles/Home.css
I have completed the issue that is assigned to me #34 of this project and after changes it looks like
https://github.com/user-attachments/assets/dd3929ed-9786-4620-81e1-6b5250949777
> Add feature: New Scroll Bar added. Completed the assign issue #34 done.

- README.md
- client/package-lock.json
- client/src/modules/OPD/HospitalList.jsx
- client/src/modules/OPD/HospitalPanal.jsx
- client/src/modules/OPD/Registration.jsx
- client/src/modules/common/AuthForm.jsx
- client/src/modules/common/Profile.jsx
- client/src/modules/common/userContext.jsx
- client/src/styles/UserProfile.css
- server/index.js
Styling of the user profile page completed
> Styled the User Profile Page

- client/package-lock.json
- client/src/modules/OPD/Registration.jsx
- client/src/styles/OPD.css
**Description**
This PR implements comprehensive validation checks for the OPD Registration Form to enhance user experience and data integrity. The following improvements have been made:
- Mandatory fields for name, age, gender, contact number, address, department, and symptoms.
- Enhanced layout and styling for better usability.
- Clear error message styling for validation feedback.
- Adjusted button states for disabled scenarios.
- Ensure data integrity and improve user experience for OPD service users.
**Additional Notes**
- The code has been tested for functionality and responsiveness.
- I am open to further suggestions and improvements from the maintainers.
> Added proper validation and ui for OPD registration form

- client/src/modules/common/Profile.jsx
- client/src/styles/UserProfile.css
User profile page is now responsive, kindly check.
> Made the userprofile page responsive

- client/src/modules/OPD/Review.jsx
working fine #45 and #64 done which are assigned to me .
https://github.com/user-attachments/assets/828b0f58-fc2e-42be-97b7-3e7871d637a1
> people review section working properly : working properly What Our Patients Say section

- .env.example
- .gitignore
- client/package-lock.json
- client/src/modules/OPD/Registration.jsx
- server/index.js
Add a field email and fix the registration route. Solves the issue #68
> Update a field email and fix the registration form

- client/src/modules/common/AuthForm.jsx
fixed: #70 
Demo:
https://github.com/user-attachments/assets/08995619-4f7e-4d42-8fb3-9f3e7a415880
> Register link issue fix

- client/src/modules/OPD/Home.jsx
#32 fixes close
Hence Added Images
> #32 Added Images and made it responsive

- client/package-lock.json
- client/package.json
- client/src/modules/OPD/Review.jsx
> Upstyled the review cards

- .github/workflows/greetings.yml
Resolved bugs:
Change of configurations for Add greetings bot.
> Changes made on Add greetings configurations

- .env.example
- client/src/modules/OPD/Registration.jsx
> Update registration form for emergency route

- README.md
- client/Dockerfile
- docker-compose.yaml
- server/Dockerfile
- server/index.js
I have set up Dockerfiles for both the client and server components of the project. In the main root directory, I have created a docker-compose.yaml file that builds both the frontend and backend, installing all the necessary dependencies already present in the project. There is no need to add your own MongoDB connection string, as I have configured it within Docker itself. This setup allows users to run the project via Docker, sharing the MongoDB database, with information persisted whenever the containers are running. Additionally, I will update the README.md file to provide clear instructions on how to configure the project using Docker.
> Added DockerFile | Updated Readme.md

- README.md
- client/.prettierignore
- client/.prettierrc
- client/package-lock.json
- client/package.json
- server/.prettierignore
- server/.prettierrc
- server/package-lock.json
- server/package.json
Added '**format**' and '**format-check**' scripts to client and server package.json for consistent code formatting. 
Run with `npm run format` and `npm run format-check` .
> Fixes #104 | Configure prettier for code consistency.

- client/src/styles/Footer.css
I have updated the Footer of the Website
> Footer Updated issue Resolved #102

- IMPLEMENTATION.md
---
This PR introduces a detailed roadmap for the implementation of **Medi-Connect**, including:
- SWOT analysis of the medical sector in India.
- Strategy for the platform's development, launch, and post-launch phases.
- Competitor analysis with key shortcomings of major players.
- Pricing model, with freemium and premium options.
- Marketing strategy across pre-launch, launch, and post-launch phases.
---
- Issue #33 
---
- Added a comprehensive **Implementation.md** file that outlines the roadmap for Medi-Connect, covering SWOT analysis, strategy, competitor analysis, pricing, and marketing.
- The file includes a clear strategy for each phase, along with contributor guidelines.
- Markdown structure and rich text formatting ensure clarity and easy readability.
---
---
> made Implementation.md

- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/index.css
This PR solves #125 
add a custom cursor for the website which is align with the design and theme of the website.
it is responsive and maintain usability on both desktop and mobile views.
The custom cursor  have smooth transitions and smooth animation on hover over a button or link
After changes: 
[Screencast from 2024-10-04 00-28-37.webm](https://github.com/user-attachments/assets/132f12fa-4cc1-49bc-8d5e-da57efad6418)
> feat: add a Custom Cursor

- client/src/modules/common/Footer.jsx
- client/src/styles/Footer.css
**this PR addresses the ISSUE NO. : #128**
the Logic Behind the implementation of the ScrollToTop button:
1>the User only sees the ScrollToTop button when the User Scroll upto the some amount of the webpage then it will be visible.
[screen-capture (9).webm](https://github.com/user-attachments/assets/86ed46d1-2885-4118-8de5-f2db0f2f7cc1)
> added "scrollToTop" functionality.

- server/index.js
- server/modules/dashboard/authRoute.js
When pincode is submitted to backend it converts this to its lat long and saves it in the database along with the pincode
> Converts pincode to lat long while registering hospital

- client/src/styles/Login.css
Fixed #120 
Fixed css of both register and login button
> fixed the design of login and register button #120

- client/package-lock.json
- client/package.json
- client/src/modules/OPD/Home.jsx
- client/src/modules/OPD/PatientDistributionChart.jsx
- client/src/modules/OPD/TableComponent.jsx
- client/src/modules/common/FloatingIcons.jsx
**Issue No:** #103 
**Description:**
-Added Framer-Motions
-Floating Icons 
-Improve Gradient
--Avoided Using Direct Images:
-Added Table Component
-Added PieChart Component
**Output:**
https://github.com/user-attachments/assets/bbb1ceb9-4af2-497c-8e17-f9b63f4a9579
> Improved  Landing Page and Research and Data Section

- client/src/modules/OPD/Home.jsx
- client/src/styles/Home.css
**Issue No:** #103 
**Description:**
Fixed Scroll Bar that Change on PR #151
> Fixed Scroll Bar & Changed Color to Blue

- client/src/modules/OPD/Registration.jsx
- client/src/styles/OPD.css
Issue #147 
new pr raised reference with pr #154
> Enhanced OPD Form with Report Upload and UX Improvements 

- README.md
I have added all the contributors in readme.md file to give them appreciation.
Completed #186
> Additon of All Contributors | Issue #186

- client/package-lock.json
- client/package.json
- client/src/modules/OPD/HospitalList.jsx
- client/src/modules/OPD/Registration.jsx
- client/src/styles/OPD.css
- i have created OPD card that is containing the response data of the form 
- on confirming a appointment the user is redirected to User Profile .
> Instant OPD card and redirecting to user profile on confirmation of appointment

- client/src/modules/OPD/Review.jsx
fixes #153 
Also changed some font colors to match latest UI
https://github.com/user-attachments/assets/a97e6b51-858e-477d-99f4-5f4ea8a597f4
> Review Card Fixed

- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/modules/OPD/Home.jsx
- client/src/modules/common/AnimatedCursor.jsx
- client/src/modules/common/Loader.jsx
- client/src/styles/AnimatedCursor.css
- client/src/styles/Home.css
This PR addresses Issue No. #155
**1>Enhanced Cursor Behavior:**
- Improved the cursor effects to provide a smoother experience when hovering over elements. The updated cursor design creates a more visually appealing interaction.
**2>Button Interaction Feedback:**
- Added CSS properties to enhance the button click effect. The new styles provide a more tactile feedback experience, making it feel as if the button is being pressed when clicked. This improvement aims to offer a user-friendly feel when interacting with buttons.
Here is the ScreenRecording:
[screen-capture (10).webm](https://github.com/user-attachments/assets/c61e2ef8-b9b0-4251-ac35-93400069b717)
> Improve Cursor Effect for Enhanced User Experience.

- client/src/modules/OPD/Home.jsx
this PR Addresses the Issue No. : #156 
here is the ScreenRecording.
[screen-capture (12).webm](https://github.com/user-attachments/assets/20e74f9e-a581-4b99-b745-1d7271d47b41)
> Implement Loader Page for Improved User Experience

- client/package-lock.json
- client/src/modules/OPD/Registration.jsx
- client/src/styles/OPD.css
i added Med space logo and title in the header and copywrite in the footer od OPD modal 
**please add level2 and gssoc-ext label before merge**
> Added header and footer in modal  issue #217

- client/src/modules/common/Service.jsx
> Updated to remove the read more phrase

- client/src/modules/OPD/Cards.jsx
- client/src/modules/OPD/Home.jsx
- client/src/modules/OPD/HospitalList.jsx
- client/src/modules/OPD/PatientDistributionChart.jsx
- client/src/modules/OPD/TableComponent.jsx
- client/src/modules/common/About.jsx
- client/src/modules/common/FloatingIcons.jsx
- client/src/modules/common/Footer.jsx
- client/src/modules/common/Profile.jsx
- client/src/modules/common/Service.jsx
- client/src/modules/common/Sidebar.jsx
fixes #226 
fixes all `ESLint` warnings.
And finally a green clean terminal @Luson045  😅😅.
would really suggest adding a pre-commit hook for no more ESLint warnings #274.
> Fixed all ESLint warnings

- client/package-lock.json
- client/src/App.js
- client/src/modules/common/Footer.jsx
- client/src/modules/common/TermsAndConditions.jsx
Added New Page  for terms with eye-catchy design
> Added new Page for terms

- .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- Fixes #259 
- BUG Report
- Feature Request
- Pull Request [ PR ]
> [FIX] Bug, Feature and Pull Request Preset Added

- client/src/modules/OPD/Registration.jsx
- client/src/modules/common/AuthForm.jsx
- client/src/styles/Loader.css
-Added a Loader for Instant OPD page and Login page 
-when the user click on register or login loader starts and when response is generated loader stops
https://github.com/user-attachments/assets/d95239e6-0b5f-4b64-9a93-66053918bebf
> loader added on login and instant OPD

- client/src/modules/common/Navbar.jsx
- client/src/styles/Navbar.css
Login and register buttons are made responsive.
> login and register buttons are adjusted for mobile screens inside the Navbar.

- client/package-lock.json
- client/src/App.js
- client/src/modules/comps/ScrollToTop.js
This PR adds the feature of auto scroll to top while navigating between pages. And closes the issue #263 
@Luson045 please review it
> add: scrolltotop feat while navigation

- client/src/modules/common/Navbar.jsx
- client/tailwind.config.js
- Fixes navbar responsive issue in mobile view.
- #295 
https://github.com/user-attachments/assets/167bea40-911a-48c4-a907-432c57950b9b
> Fix:Navbar responsive issue in mobile view

- client/src/modules/Registration/StepOne.jsx
- client/src/modules/Registration/StepTwo.jsx
This PR adds red asterisks to all the compulsory fields in the registration form and closes the issue #265 
@Luson045 please review and merge
> [feat]: add red asterisks to all the compulsory fields

- client/src/modules/Registration/StepOne.jsx
This PR adds validation checks for email addresses and closes the issue #264 
@Luson045 @ROKUMATE please review this
> add: validation of email address

- client/src/styles/UserProfile.css
> Changed the padding for mobile view.

- client/src/modules/Registration/StepOne.jsx
- server/modules/dashboard/authRoute.js
This PR addresses [#294](#) by enhancing password security. It enforces the following validation rules:
- At least one uppercase letter
- At least one number
- At least one special character
These changes strengthen the authentication process, ensuring more secure password creation both in the frontend and backend.
> 🔒 Enhance password validation with stronger security rules

- client/src/modules/common/Service.jsx
This pull request resolves the spelling mistake where "service" was incorrectly spelled as "servives" in the Services component.
**Issue Related**
#326 
Corrected the word "servives" to "services" in the Services component.
> spelling corrected

- client/src/App.js
- client/src/modules/common/Footer.jsx
- client/src/modules/common/TermsAndConditions.jsx
> Terms and Condition Page

- client/src/modules/LabTest/LabTest.jsx
fix that small hover issue, But I can't find the page load time issue its just working fine.
>  Fixed the text disappears on hover effect and did mini changes

- server/modules/dashboard/authRoute.js
Fixes #284 
Fixed zod validation schema for dob.
> Chore : fixed zod schema for dob

- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/modules/common/HospitalsAround.jsx
- client/src/modules/common/Navbar.jsx
Hi! this is the new PR regarding the issue - Implementing maps for nearby hospitals!
> added hospitals-around in updated code-issue 228

- client/src/modules/common/Footer.jsx
- client/src/modules/common/GoogleTranslate.jsx
**ISSUE** #317 
I complete this.
Please don't forget to add this label --> *gssoc24-exted, hacktoberfest-accepted, label-2* as per added in the issue #317 
merge it.
> Issue #317 Fixed the footer from scratch

- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/index.js
- client/src/modules/LabTest/LabTest.jsx
- client/src/modules/common/Footer.jsx
- client/src/modules/common/Medical-Chatbot/Chatbot.jsx
- client/src/modules/common/Navbar.jsx
- client/src/modules/common/ScrollProgressIndicator.jsx
- client/src/styles/ScrollProgressIndicator.css
- package.json
Fixes: #328 
Added Progress bar indicator at top on scroll view.
Demo:
https://github.com/user-attachments/assets/09a52ba7-6ad5-4e2e-a86c-43fa941f73fd
> Feat: Added progress indicator on scroll

- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/index.js
- client/src/modules/LabTest/LabTest.jsx
- client/src/modules/common/Footer.jsx
- client/src/modules/common/Medical-Chatbot/Chatbot.jsx
- client/src/modules/common/Navbar.jsx
- client/src/modules/common/ScrollProgressIndicator.jsx
- client/src/styles/ScrollProgressIndicator.css
- package.json
fixes: #371 
Changes in pr:
- Fixed the chat button position
- Made both Chat and Go to top button uniform with same `bg` and hover color.
Demo
> Fixed chatbot position

- client/package-lock.json
- client/package.json
- client/src/modules/Registration/StepOne.jsx
- client/src/modules/Registration/StepTwo.jsx
- client/src/modules/common/Medical-Chatbot/Chatbot.jsx
Fixes: #385
Changes in PR:
- Fixed setBasicDetails
- Improved validation for form registration
- Added lodash to check empty array
> Fixes : setBasicDetails-undefined

- client/src/Medical-Chatbot/Chatbot.jsx
- client/src/components/Footer.jsx
- client/src/components/Layout.jsx
> bug fix for scroll to top

- client/src/pages/HospitalsAround.jsx
> hospital around simple card desgined

- client/src/components/Footer.jsx
- client/src/components/Navbar.jsx
- client/src/pages/BlogDetailsPage.jsx
Fixes #408 
**Screenshot:**
https://github.com/user-attachments/assets/06da9dcc-a8e6-4b9a-ab73-18191098b36d
> Added Navbar and Footer on all blog pages

- client/src/components/BusinessContactForm.jsx
- client/src/components/Footer.jsx
- client/src/components/Layout.jsx
The BusinessContactForm is a React component that collects contact information from potential clients interested in Medi-Connect's healthcare solutions. It features a two-step process, responsive design, and gathers essential details about the business and their interests. The form uses Tailwind CSS for styling and React hooks for state management, ensuring a user-friendly experience across different devices.
> Create a business contact form in contact us section medi-connect.

- client/src/pages/AuthForm.jsx
**Linked Issue**:  
This PR resolves the issue : #407
**Description**:  
This pull request addresses the following issues on the login page:
1. The login header, which was previously styled like normal text, has been made more prominent by adjusting its font size and weight for better visibility.
2. The `user type` input field height has been aligned with the `email` and `password` input fields to ensure visual consistency.
**Changes Made**:
- Updated the CSS for the login header to increase the font size and make the text bold.
- Adjusted the CSS for the `user type` input field to match the height of the `email` and `password` fields.
**Use Case**:  
The changes ensure that users have a better experience when logging in, with a clear distinction between the header and the rest of the …
> Fix Login Page Header and User Type Input Field Height Consistency

- client/src/components/Navbar.jsx
- client/src/components/ReviewDetails.jsx
- client/src/components/StepTwo.jsx
- server/validators/authSchemas.js
Closes #404 
Changes in PR
- Added spinner for registration
- Added validation to back button 
So that user is not able to go back to previous step once he clicks on `register` button.
- Consistent with dark theme
Demo:
https://github.com/user-attachments/assets/23a87476-1267-491b-98d8-9dfb4ba11a51
> Feat : Added spinner for registration

- client/src/components/Layout.jsx
- client/src/components/ReviewDetails.jsx
- client/src/data/databaseUrls.js
- client/src/pages/AuthForm.jsx
- client/src/pages/HospitalDetail.jsx
- client/src/pages/HospitalList.jsx
- client/src/pages/HospitalPanal.jsx
- client/src/pages/OPDRegistration.jsx
- client/src/pages/OPDSchedule.jsx
- client/src/pages/Profile.jsx
- client/src/store/userContext.jsx
- server/controllers/user/profileController.js
- server/models/hospital.js
- server/routes/user/profile.js
> Add OPD Schedule Page

- client/src/Medical-Chatbot/Chatbot.jsx
> changes: chatbot darmode fix and chatbot width bug fix

- client/src/pages/BlogDetailsPage.jsx
back button added : back button added on blogs page and where needed #425 done
check its responsiveness it is looking good and added on every blog post.
> back button added : back button added on blogs page and where needed #425 done

- client/package-lock.json
- client/src/components/Description.jsx
- client/src/pages/About.jsx
I have fixed Ui of aboutUs section, has made several changes in bgColor,textColor and more.
I have made sure it works fine responsively.
To equalise the size of all cards, I have added ReadMore functionality
Fixed #370 
Please attach all the badges while merging too.(gssoc-ext,hactoberfest-accepted,level-2)
**I would appreciate if you could give me level3 bage.**
Thanks :)
> UI Enhanced of AboutUs Section

- client/package-lock.json
- client/package.json
- client/src/pages/HospitalsAround.jsx
- client/src/styles/Nearbyhospitals.css
nearby hospital route showing : #426 done
the changes i have made in  #426 -
1. adding route from current location to hospital.
2. showing total distance from hospital to current location.
3. made current location in human readable form.
4. Route is showing on responsive mode also.
https://github.com/user-attachments/assets/e93752ad-11f2-4eca-bf89-e81725c8c51f
> nearby hospital route showing : #426 done

- client/src/components/Footer.jsx
- client/src/components/GoogleTranslate.jsx
> Fix Translate Dropdown Persistence in Footer

- client/package-lock.json
- client/src/pages/OPDRegistration.jsx
added validation here 
**please add gssoc-ext and level1 before merge** @Luson045
> added validation in booking date

- client/src/components/Review.jsx
- client/src/pages/About.jsx
Now the about section has proper alignment for all cards
Community says section is fixed for dark mode
https://github.com/user-attachments/assets/86ae20d7-055d-48d1-915d-a8b928ecfe2d
> fixed dark mode and alignment #430

- client/src/Medical-Chatbot/Chatbot.jsx
- client/src/components/Footer.jsx
Fixes: #444
Removed the duplicate chatbot button appearing at the top of footer.
> Fixed the unnecessary chatbot button

- client/src/components/MultiStepRegistration.jsx
- client/src/components/StepTwo.jsx
Fixes: #392 
Changes in PR:
- Added validation for next step
Demo: 
https://github.com/user-attachments/assets/4eb910f0-7140-49ab-9705-e1648e4ab4cc
> chore: Added next step validation

- client/src/pages/AuthForm.jsx
- server/.env.example
- server/controllers/auth/authController.js
- server/index.js
- server/models/hospital.js
- server/models/user.js
- server/routes/auth/auth.js
- server/utils/otputils.js
- server/validators/authSchemas.js
In login page there is "Don't have an account?/Register" get invisible in dark mode so i have solve it now in dark mode text become white in color whereas in light mode it become black in color
> Solve dark mode visibility in login page

- client/src/components/Navbar.jsx
Fixes:#496
This PR makes sure that Allignment fixes.
@Luson045 assign my other issues as well , so that i can contribute.
> Fixes:#496 - Allignment of navbar fixed.

- client/src/components/Navbar.jsx
Reverts Luson045/medi-connect#504
> Revert "Fixes:#496 - Allignment of navbar fixed."

- client/src/components/StepOne.jsx
> color changes in dark mode

- client/src/components/Navbar.jsx
Finally we fixed it , made it perfect.
https://github.com/user-attachments/assets/b587a65b-fcb0-4de4-ae18-0d08ad4e1f66
Please assign my other issue as well ,
> Fixes:#496/navbar-allign

- client/src/data/databaseUrls.js
- client/src/pages/AuthForm.jsx
- server/controllers/auth/authController.js
- server/utils/cors/corsConfig.js
login page user/hospital selection added : #483 done
Now your login is working fine. 
https://github.com/user-attachments/assets/75000d6d-f298-428d-bf07-f717acd2d447
If possible can you merge fast so i can start working on 468 issue no because i have to pull this then i can make changes on it.
> login page user/hospital selection added : #483 done

- CONTRIBUTING.md
I have enhanced the structure of the contributing.md file and also added some new sections. Added the screenshots also of the sections which all I have added.
Changes I have made :-
1) Enhanced the project structure
2) Added Code of conduct that was given in the project
3) Added need help with the basics section
4) Add project structure section
5) Add additional method of contributing through GitHub desktop section
6) Add good coding practices section
7) Add the help and support section
8) Add the pull request section
9) Add issue report process section
fixes:[#488 ]
closes:[#488 ]
> Enhanced the structure and also added some new sections

- README.md
https://github.com/user-attachments/assets/ef2ac859-a78f-471a-9fbd-172af64b34bf
Please label this PR with:
- gssoc-ext for contributions under GirlScript Summer of Code Extended.
- hacktoberfest-accepted to ensure it counts towards Hacktoberfest.
> Updated README with additional details and badges

- client/src/components/Navbar.jsx
- client/src/privateroute/privateroute.jsx
- client/src/store/userContext.jsx
#468 done 
Added private routes on navbar.
Added hospital page.
Added lab test on only profile page.
Added icon and login user name on navbar instead of just written profile.
Screenshot and video -
https://github.com/user-attachments/assets/2a56fd35-9980-499c-aa23-1eff71662c83
> private routes and hospital page added : #468 done

- client/src/pages/LabTest.jsx
Feature#492: Enhance LabTest Cards to include more details. Redirect to the Hospitals page when clicked 'Read More'.
1. The lab test card now contains more details on a lab test like price and ratings.
2. Redirection to 'Hospitals-around'  page when clicked 'Read More'.
> Feature#492: Enhance LabTest Cards to include more details. Add redirection for 'Read More'.

- client/src/components/Navbar.jsx
issue_number: #528 
improving button styled added some hover and animation is added also added animation to icons
https://github.com/user-attachments/assets/1c38393e-178d-48b2-980c-149359df0d07
> Button and icons hover and animation added

- client/src/pages/About.jsx
issue_number: #530 
Added 3d hover effect and animation to social media icons of cards icon
https://github.com/user-attachments/assets/9c9bf985-4ee3-475c-9c44-ed0b641b5b03
> Added 3d hover effect and animation to cards social media icons

- client/src/App.js
- client/src/components/PreLoader.jsx
- client/src/styles/Preloader.css
Solved :
Issue no #395 
https://github.com/user-attachments/assets/7bc7df11-b0f2-46f1-af49-456693e67021
> Adding Animated Preloader

- client/src/components/Review.jsx
**Issue #531** 
I have successfully done the proposed changes in '**What Our Community Says section**' section of Landing Page , by updating the **slider of reviews** of Users.
Changes are :
> Fixed slider in What Our Community Says section

- client/src/pages/About.jsx
- client/src/pages/HospitalList.jsx
- client/src/pages/Service.jsx
Issue - #561 
Change the background color of some pages on the dark theme as it was not changing according to the theme.
Made Changes in About, Hospital, and Services Page.
> Change Background Color on Dark Theme

- client/package-lock.json
- client/src/components/Footer.jsx
- client/src/components/Navbar.jsx
- client/src/pages/Profile.jsx
- client/tailwind.config.js
> Match Footer Background with Navbar in Dark Theme

- client/src/components/ForgotPassword.jsx
You can toggle the show and hide the password visibility on the forgot password page.
#544 done 
https://github.com/user-attachments/assets/2f5c4a50-5237-4d08-a6f8-bf1079b2b043
> password show hide icon : Password visible option added on forgot password page.

- client/src/components/MultiStepRegistration.jsx
- client/src/styles/Login.css
- client/src/styles/OPD.css
Issue - #565 
I modified the registration, and OPD form design in the light and dark theme to match the design of the dark theme, there is a background animation that creates a smooth color transition effect on both themes.
> Enhance Registration Form background design 

- client/package-lock.json
- client/package.json
- client/src/components/MultiStepRegistration.jsx
- Enhanced the CSS styling of the Login and Registration pages to align with the website's color palette.
- Adjusted fonts, buttons, and input fields to create a more cohesive design with the website’s theme.
- Fixed issues with the header layout to improve user experience, ensuring better accessibility and responsiveness.
- Improved header design by making it more intuitive and easy to navigate.
- Closes #585 
- The design changes were made based on the website's color palette and user feedback.
- The header fix should resolve previous alignment issues on mobile and desktop views.
After:
> Fixed the Navbar for better UX and change the css of logon and register according to the color pallet of Website i Dark mode
